/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-12 11:53:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.host.model.vo.SpaceImageFile;
import java.util.List;
import com.kh.host.model.vo.Space;
import com.kh.host.model.vo.SpacePrice;
import java.util.ArrayList;
import com.kh.host.model.vo.SpaceDayOff;

public final class spaceCheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1565600118659L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1565600118699L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.kh.host.model.vo.SpaceDayOff");
    _jspx_imports_classes.add("com.kh.host.model.vo.SpaceImageFile");
    _jspx_imports_classes.add("com.kh.host.model.vo.Space");
    _jspx_imports_classes.add("com.kh.host.model.vo.SpacePrice");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>KH Space</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/moonspam/NanumBarunGothic@1.0/nanumbarungothicsubset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/slick-theme.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/js/common.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/js/slick/slick.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=> {\r\n");
      out.write("\t$(\"#spaceSrch\").keyup(e => {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $sel = $(\".sel\");\r\n");
      out.write("\t\tvar $li = $(\"#autoComplete li\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(e.key == \"ArrowDown\"){\r\n");
      out.write("\t\t\tif($sel.length == 0){\r\n");
      out.write("\t\t\t\t$li.eq(0).addClass(\"sel\");\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\telse if($sel.is($li.last())){\r\n");
      out.write("\t\t\t\t//처리코드 없음\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\")\r\n");
      out.write("\t\t\t\t    .next()\r\n");
      out.write("\t\t\t\t    .addClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(e.key == \"ArrowUp\"){\r\n");
      out.write("\t\t\tif($sel.length == 0){\r\n");
      out.write("\t\t\t\t//처리코드 없음\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\telse if($sel.is($li.first())){\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\")\r\n");
      out.write("\t\t\t\t    .prev()\r\n");
      out.write("\t\t\t\t    .addClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(e.key == \"Enter\"){\r\n");
      out.write("\t\t\t//값입력\r\n");
      out.write("\t\t\t$(e.target).val($sel.text());\r\n");
      out.write("\t\t\t//#autoComplete 감춤\r\n");
      out.write("\t\t\t$(\"#autoComplete\").hide()\r\n");
      out.write("\t\t\t\t\t\t\t  .children()\r\n");
      out.write("\t\t\t\t\t\t\t  .remove();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar spaceSrch = $(e.target).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//사용자입력값이 없는 경우, 조기 리턴처리함.\r\n");
      out.write("\t\t\tif(spaceSrch.trim().length == 0)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/search/autoComplete.do\",\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tdata:\"spaceSrch=\"+spaceSrch,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.trim().length == 0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#autoComplete\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tvar nameArr = data.split(',');\r\n");
      out.write("\t\t\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\t\t\t$.each(nameArr, (i, name)=>{\r\n");
      out.write("\t\t\t\t\t\t\tname = name.replace(spaceSrch,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"<span class='srchVal'>\"+spaceSrch+\"</span>\");\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<li>\"+name+\"</li>\";\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#autoComplete\").html(html)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  .fadeIn(200);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//마우스 이벤트 핸들러 추가\r\n");
      out.write("\t\t\t\t\t$(\"#autoComplete li\")\r\n");
      out.write("\t\t\t\t\t\t.click(e=>{\r\n");
      out.write("\t\t\t\t\t\t\t//값입력\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#spaceSrch\").val($(e.target).text());\r\n");
      out.write("\t\t\t\t\t\t\t//#autoComplete 감춤\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#autoComplete\").hide()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  .children()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  .remove();\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t.hover(e=>{\r\n");
      out.write("\t\t\t\t\t\t\t$(e.target).addClass(\"sel\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   .siblings()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   .removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}, e=>{\r\n");
      out.write("\t\t\t\t\t\t\t$(e.target).removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <h1 id=\"logo\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"dp_block fw700\"><span>KH</span> Space</a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div id=\"search-area\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() );
      out.write("/search/spaceFinder\" method=\"get\" name=\"spaceSearchFrm\"  class=\"dp_block clearfix\">\r\n");
      out.write("                <input type=\"text\" name=\"spaceSrch\" id=\"spaceSrch\" placeholder=\"지역 또는 공간유형을 검색해보세요!\">\r\n");
      out.write("                <input type=\"submit\" id=\"srchBtn\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("                <ul id=\"autoComplete\"></ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath() );
      out.write("/host/spaceEnroll\" class=\"go-space dp_block\">공간 등록하기</a>\r\n");
      out.write("        <div class=\"menu-btn clearfix\">\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <p></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"nav_wrap\">\r\n");
      out.write("    \t<div>\r\n");
      out.write("\t        <div id=\"nav-top\" class=\"clearfix\">\r\n");
      out.write("\t            <div class=\"menu-close\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/close.png\" alt=\"\" width=\"24px\"></div>\r\n");
      out.write("\t            <div class=\"nav-ico\"></div>\r\n");
      out.write("\t            <p>\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib fw600\">로그인</a>이 필요합니다.\r\n");
      out.write("\t            </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <nav id=\"menu\">\r\n");
      out.write("\t            <ul class=\"menu1\">\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"dp_block\">KH Space Home</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">내 정보 보기</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/booking/bookingList?userId=datbot\" class=\"dp_block\">예약 리스트</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">찜한 공간</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/spaceList\" class=\"dp_block\">전체 공간보기</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">추천 공간</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/board/adminNote\" class=\"dp_block\">공지사항</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/banner/information\" class=\"dp_block\">배너 등록</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/spaceChkList\" class=\"dp_block\">관리자 공간 검수 리스트</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </nav>\r\n");
      out.write("\t        <div id=\"nav-bottom\" class=\"txt_center\">\r\n");
      out.write("\t            <div class=\"clearfix\">\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib\">로그인</a>\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib\">회원가입</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <p>Copyright KH SPACE Corp. All Rights Reserved.</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"dim-layer\"></div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	int spaceNo = Integer.parseInt(request.getParameter("spaceNo"));
	Space s = (Space)request.getAttribute("space");
	List<SpaceImageFile> sImg = (List<SpaceImageFile>)request.getAttribute("spaceImg");
	List<SpacePrice> sPrice = (List<SpacePrice>)request.getAttribute("sPrice");
	List<SpaceDayOff> sDayOff = (List<SpaceDayOff>)request.getAttribute("sDayOff");
	
	boolean bool = false; //이벤트 여부 체크
	int spacePrice = 0; //공간 원래 가격
	boolean alwaysEvent = false; //정기 이벤트 여부
	boolean notAlwaysEvent = false; //비정기 이벤트 여부
	String alwaysEventType = "";
	int alwaysEventPrice = 0;
	String alwaysEventDate = ""; //정기이벤트 날짜
	List<String> notAlwaysEventDate = new ArrayList<>(); //비정기이벤트 날짜
	String minnotAlwaysEventDate = "";
	String maxnotAlwaysEventDate = "";
	
	if(!sPrice.isEmpty()){
		for(SpacePrice sp : sPrice){
			if(sp.getPriceEvent()!=null){
				bool = true;
				if(sp.getPriceEvent().contains("일")) {
					alwaysEvent = true;
					alwaysEventType = "1개월";
					if(sp.getPriceEvent().contains("요일")){
						alwaysEventType = "1주일";
					}
					alwaysEventPrice = sp.getSpacePrice();
					alwaysEventDate = sp.getPriceEvent();
				} else if(sp.getPriceEvent().contains("-")) {
					notAlwaysEvent = true;
					notAlwaysEventDate.add(sp.getPriceEvent());
				}
			} else if(sp.getPriceEvent()==null) {
				spacePrice = sp.getSpacePrice();
			}
		}
	}
	
	if(!notAlwaysEventDate.isEmpty()){
		for(int i=0; i<notAlwaysEventDate.size(); i++){
			minnotAlwaysEventDate = notAlwaysEventDate.get(0);
			maxnotAlwaysEventDate = notAlwaysEventDate.get(notAlwaysEventDate.size()-1);
		}
	}
	
	String sDayOffDate = "";
	String sDayOffEvent = "";
	if(!sDayOff.isEmpty()){
		for(SpaceDayOff sdo :sDayOff){
			if(sdo.getMaxSpaceDayOff()!=null){
				sDayOffDate = sdo.getMaxSpaceDayOff();
			}
			if(sdo.getDayOffEvent()!=null){
				sDayOffEvent = sdo.getDayOffEvent();
			}
		}
	}
	
	String[] sDayOffDateArr = null;
	if(!sDayOffDate.equals("") && sDayOffDateArr!=null){
		sDayOffDateArr = sDayOffDate.split(",");
	}

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/sub.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/spaceEnroll.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#spaceEnrollFile\").on('change', fileCheck);\r\n");
      out.write("\tvar str = \"");
      out.print(s.getSpaceIntro()!=null?s.getSpaceIntro():"");
      out.write("\";\r\n");
      out.write("\tstr = str.split('<br/>').join(\"\\r\\n\");\r\n");
      out.write("\t$('#spaceIntro').val(str); \r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input, textarea, select\").prop(\"disabled\", true);\r\n");
      out.write("\t$(\"input[type=submit], input[name=spaceChkNo], input[name=spaceChkCancelNo]\").prop(\"disabled\", false);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function goSpaceEnrollCancel(){\r\n");
      out.write("\t$(\"form[name=spaceEnrollChkCancelFrm]\").submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"sub_container\">\r\n");
      out.write("\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/spaceChkNo\" name=\"spaceEnrollChkCancelFrm\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"spaceChkCancelNo\" value=\"");
      out.print(spaceNo);
      out.write("\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("    <section class=\"subPage spaceEnroll\">\r\n");
      out.write("        <article>\r\n");
      out.write("        \t<div class=\"spaceEnrollTit clearfix\">\r\n");
      out.write("        \t\t<h3 class=\"tit\">어떤 공간을 공유하실건가요?</h3>\r\n");
      out.write("        \t\t<p class=\"req\">필수 선택</p>\r\n");
      out.write("        \t</div>\r\n");
      out.write("            <p class=\"req\">신중하게 공간 유형을 선택해주세요!</p>\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() );
      out.write("/admin/spaceChk\" name=\"spaceEnrollChkFrm\" \r\n");
      out.write("            \t\tmethod=\"post\" onsubmit=\"return true;\">\r\n");
      out.write("            \t<input type=\"hidden\" name=\"spaceChkNo\" value=\"");
      out.print(spaceNo);
      out.write("\" />\r\n");
      out.write("            \t<div class=\"clearfix\">\r\n");
      out.write("            \t\t<h4>공간유형<span class=\"req\">*</span></h4>\r\n");
      out.write("            \t\t<p>최대 5개 선택 가능</p>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<ul class=\"facility-list space-list clearfix\">\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType0\" value=\"스터디룸\" ");
      out.print(s.getSpaceThema().contains("스터디룸")?"checked":"");
      out.write(" >\r\n");
      out.write("\t                    <label for=\"spaceType0\">스터디룸</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType1\" value=\"공연장\" ");
      out.print(s.getSpaceThema().contains("공연장")?"checked":"");
      out.write(">\r\n");
      out.write("\t                    <label for=\"spaceType1\">공연장</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType2\" value=\"세미나실\" ");
      out.print(s.getSpaceThema().contains("세미나실")?"checked":"");
      out.write(">\r\n");
      out.write("\t                    <label for=\"spaceType2\">세미나실</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType3\" value=\"파티룸\" ");
      out.print(s.getSpaceThema().contains("파티룸")?"checked":"");
      out.write(">\r\n");
      out.write("\t                    <label for=\"spaceType3\">파티룸</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType4\" value=\"카페\" ");
      out.print(s.getSpaceThema().contains("카페")?"checked":"");
      out.write(">\r\n");
      out.write("\t                    <label for=\"spaceType4\">카페</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType5\" value=\"기타\" ");
      out.print(s.getSpaceThema().contains("기타")?"checked":"");
      out.write(">\r\n");
      out.write("\t                    <label for=\"spaceType5\">기타</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("            \t<h4>대표이미지<span class=\"req\">*</span></h4>\r\n");
      out.write("            \t<p>이미지 사이즈 : 1024*450, 크기 : 10MB 권장</p>\r\n");
      out.write("            \t<div class=\"clearfix\">\r\n");
      out.write("            \t\t<div id=\"enrollImg1\" class=\"spaceEnroll-img\">\r\n");
      out.write("            \t\t");
 if(!sImg.isEmpty()){
            			for(SpaceImageFile s1 : sImg){
            			if(s1.getImageRenamedFileName()!=null && s1.getFlag().equals("Y")){
            		
      out.write("\r\n");
      out.write("            \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/host/");
      out.print(s1.getImageRenamedFileName() );
      out.write("\" alt=\"\" height=\"110\" />\r\n");
      out.write("            \t\t");
		
            			} }
            		} 
      out.write("\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"filebox\"> \r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFile\">파일 첨부</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFile\" id=\"spaceEnrollFile\" class=\"upload-hidden\">\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<h4>이미지</h4>\r\n");
      out.write("            \t<p>이미지 사이즈 : 1024*450, 크기 : 10MB 권장(1장당), <span>최대 3장 업로드 가능</span></p>\r\n");
      out.write("            \t<div class=\"multipleFile clearfix\">\r\n");
      out.write("            \t\t<div id=\"enrollImg2\" class=\"spaceEnroll-img\">\r\n");
      out.write("            \t\t");
 if(!sImg.isEmpty()){
            			for(SpaceImageFile s2 : sImg){
            			if(s2.getImageRenamedFileName()!=null && s2.getFlag().equals("N")){
            		
      out.write("\r\n");
      out.write("            \t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/upload/host/");
      out.print(s2.getImageRenamedFileName() );
      out.write("\" alt=\"\" height=\"110\"/>\r\n");
      out.write("            \t\t");
		
            			} }
            		} 
      out.write("\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"filebox\"> \r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg1\">파일 첨부1</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg1\" id=\"spaceEnrollFileImg1\" class=\"upload-hidden\">\r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg2\" style=\"margin: 14px 0;\">파일 첨부2</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg2\" id=\"spaceEnrollFileImg2\" class=\"upload-hidden\">\r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg3\">파일 첨부3</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg3\" id=\"spaceEnrollFileImg3\" class=\"upload-hidden\">\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<h4>공간 정보</h4>\r\n");
      out.write("            \t<div id=\"spaceEnroll-wrap\">\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간명<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceName\" id=\"spaceName\" class=\"inputStyle dp_block\" value=\"");
      out.print(s.getSpaceName()!=null?s.getSpaceName():"");
      out.write("\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간 슬로건</h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceSlogan\" id=\"spaceSlogan\" class=\"inputStyle dp_block\" value=\"");
      out.print(s.getSpaceSlogan()!=null?s.getSpaceSlogan():"");
      out.write("\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간 소개<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p><textarea name=\"spaceIntro\" id=\"spaceIntro\" class=\"dp_block\" cols=\"30\" rows=\"10\"></textarea></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>수용인원<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p>\r\n");
      out.write("            \t\t\t\t최소 :&nbsp;\r\n");
      out.write("            \t\t\t\t<span class=\"bookingsrchPrice srchPrice dp_ib\"><input type=\"number\" name=\"minBookingPeople\" id=\"minBookingPeople\" value=\"");
      out.print(s.getMinBookingPeople());
      out.write("\" class=\"dp_block\" /></span>\r\n");
      out.write("            \t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;최대 :&nbsp;\r\n");
      out.write("            \t\t\t\t<span class=\"bookingsrchPrice srchPrice dp_ib\"><input type=\"number\" name=\"maxBookingPeople\" id=\"maxBookingPeople\" value=\"");
      out.print(s.getMaxBookingPeople());
      out.write("\" class=\"dp_block\" /></span>\r\n");
      out.write("            \t\t\t</p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>해시태그&nbsp;&nbsp;<span class=\"req\">쉼표(,)로 구분</span></h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"hashTag\" id=\"hashTag\" class=\"inputStyle dp_block\" value=\"");
      out.print(s.getHashtag()!=null?s.getHashtag():"");
      out.write("\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>편의시설</h5>\r\n");
      out.write("           \t\t\t\t<ul class=\"facility-list clearfix\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility0\" value=\"주차\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("주차")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility0\">주차</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility1\" value=\"흡연\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("흡연")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility1\">흡연</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility2\" value=\"와이파이\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("와이파이")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility2\">와이파이</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility3\" value=\"컴퓨터\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("컴퓨터")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility3\">컴퓨터</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility4\" value=\"음식물 반입금지\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("음식물 반입금지")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility4\">음식물 반입금지</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility5\" value=\"콘센트\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("콘센트")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility5\">콘센트</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility6\" value=\"의자/테이블\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("의자/테이블")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility6\">의자/테이블</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility7\" value=\"반려동물 동반 가능\" ");
      out.print(s.getSpaceFacilities()!=null&&s.getSpaceFacilities().contains("반려동물 동반 가능")?"checked":"");
      out.write(">\r\n");
      out.write("                                <label for=\"facility7\">반려동물 동반 가능</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>가격<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p class=\"srchPrice\">\r\n");
      out.write("            \t\t\t<input type=\"number\" name=\"spaceEnrollPrice\" id=\"spaceEnrollPrice\" class=\"dp_block\" value=\"");
      out.print(spacePrice);
      out.write("\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll enrollDayOff\">\r\n");
      out.write("            \t\t\t<h5>이벤트</h5>\r\n");
      out.write("            \t\t\t<p>이벤트 여부</p>\r\n");
      out.write("            \t\t\t<input type=\"checkbox\" name=\"spaceEnrollEvent\" id=\"spaceEnrollEvent\" ");
      out.print(bool?"checked":"" );
      out.write("/>\r\n");
      out.write("            \t\t\t<label for=\"spaceEnrollEvent\">적용</label>\r\n");
      out.write("            \t\t\t<p>정기/비정기</p>\r\n");
      out.write("            \t\t\t<div class=\"spaceEnrollEvent\">\r\n");
      out.write("            \t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollEventType\" id=\"spaceEnrollAlwaysEvent\" value=\"정기 이벤트\" ");
      out.print(alwaysEvent?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t<label for=\"spaceEnrollAlwaysEvent\" class=\"dp_ib\">정기 이벤트</label>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\" style=\"display:block;\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollAlwaysEventType\" id=\"spaceEnrollAlwaysEventType\" class=\"dp_block\" >\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1주일\" ");
      out.print(alwaysEventType.equals("1주일")?"selected":"" );
      out.write(">1주일</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1개월\" ");
      out.print(alwaysEventType.equals("1개월")?"selected":"" );
      out.write(">1개월</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t<div class=\"clearfix\" style=\"float:none; width:100%; padding-top:15px;\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollAlwaysEventDate\" id=\"spaceEnrollAlwaysEventDate\"\r\n");
      out.write("            \t\t\t\t\tvalue=\"");
      out.print(alwaysEventDate );
      out.write("\" \r\n");
      out.write("            \t\t\t\t\tplaceholder=\"이벤트 주기가 1주일이면 요일을, 1개월이면 몇일인지 입력해주세요.\" class=\"dp_ib\" style=\"display:inline-block;\"/>\r\n");
      out.write("            \t\t\t\t\t<p id=\"spaceEnrollAlwaysEventPrice\" class=\"srchPrice dp_ib\" style=\"margin-bottom:0; display:inline-block;\">\r\n");
      out.write("            \t\t\t\t\t\t<input type=\"number\" name=\"spaceEnrollAlwaysEventPrice\" value=\"");
      out.print(alwaysEventPrice );
      out.write("\" class=\"dp_ib\"/>\r\n");
      out.write("            \t\t\t\t\t</p>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t\t<div class=\"spaceEnrollEvent\">\r\n");
      out.write("            \t\t\t\t<div class=\"clearfix\" style=\"width:100%; float:none;\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollEventType\" disabled=\"disabled\" id=\"spaceEnrollNotAlwaysEvent\" value=\"비정기 이벤트\" ");
      out.print(notAlwaysEvent?"checked":"" );
      out.write(" />\r\n");
      out.write("\t            \t\t\t\t<label for=\"spaceEnrollNotAlwaysEvent\" class=\"dp_ib\">비정기 이벤트</label>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("\t            \t\t\t\r\n");
      out.write("\t            \t\t\t<div style=\"float:none; width:100%;\">\r\n");
      out.write("\t            \t\t\t\t<div class=\"dp_ib spaceEnrollNotAlwaysEventDate\" style=\"display:inline-block;\">\r\n");
      out.write("\t            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollNotAlwaysEventStartDate\" id=\"spaceEnrollNotAlwaysEventStartDate\" \r\n");
      out.write("\t            \t\t\t\t\tvalue=\"");
      out.print(minnotAlwaysEventDate );
      out.write("\" placeholder=\"ex) 2019-08-09\" class=\"eventInput dp_ib\"/>\r\n");
      out.write("\t            \t\t\t\t\t~\r\n");
      out.write("\t            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollNotAlwaysEventEndDate\" id=\"spaceEnrollNotAlwaysEventEndDate\" \r\n");
      out.write("\t            \t\t\t\t\tvalue=\"");
      out.print(maxnotAlwaysEventDate );
      out.write("\" placeholder=\"ex) 2019-08-12\" class=\"eventInput dp_ib\"/>\r\n");
      out.write("\t            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t\t<p id=\"spaceEnrollNotAlwaysEventPrice\" class=\"srchPrice dp_ib\" style=\"width:255px; margin-left:0;\"><input type=\"number\" name=\"spaceEnrollNotAlwaysEventPrice\" class=\"dp_block\" style=\"width:253px;\" /></p>\r\n");
      out.write("\t            \t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>예약 가능 시간<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t");

            				String[] bookingTime = s.getBookingTime().split("~");
            			
      out.write("\r\n");
      out.write("            \t\t\t<div>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollTime1\" id=\"spaceEnrollTime1\" class=\"dp_block\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t                            \t<option value=\"00:00\" ");
      out.print(bookingTime[0].contains("00:00")?"selected":"" );
      out.write(">00:00</option>\r\n");
      out.write("\t                            \t<option value=\"01:00\" ");
      out.print(bookingTime[0].contains("01:00")?"selected":"" );
      out.write(">01:00</option>\r\n");
      out.write("\t                            \t<option value=\"02:00\" ");
      out.print(bookingTime[0].contains("02:00")?"selected":"" );
      out.write(">02:00</option>\r\n");
      out.write("\t                            \t<option value=\"03:00\" ");
      out.print(bookingTime[0].contains("03:00")?"selected":"" );
      out.write(">03:00</option>\r\n");
      out.write("\t                            \t<option value=\"04:00\" ");
      out.print(bookingTime[0].contains("04:00")?"selected":"" );
      out.write(">04:00</option>\r\n");
      out.write("\t                            \t<option value=\"05:00\" ");
      out.print(bookingTime[0].contains("05:00")?"selected":"" );
      out.write(">05:00</option>\r\n");
      out.write("\t                            \t<option value=\"06:00\" ");
      out.print(bookingTime[0].contains("06:00")?"selected":"" );
      out.write(">06:00</option>\r\n");
      out.write("\t                            \t<option value=\"07:00\" ");
      out.print(bookingTime[0].contains("07:00")?"selected":"" );
      out.write(">07:00</option>\r\n");
      out.write("\t                            \t<option value=\"08:00\" ");
      out.print(bookingTime[0].contains("08:00")?"selected":"" );
      out.write(">08:00</option>\r\n");
      out.write("\t                            \t<option value=\"09:00\" ");
      out.print(bookingTime[0].contains("09:00")?"selected":"" );
      out.write(">09:00</option>\r\n");
      out.write("\t                            \t<option value=\"10:00\" ");
      out.print(bookingTime[0].contains("10:00")?"selected":"" );
      out.write(">10:00</option>\r\n");
      out.write("\t                            \t<option value=\"11:00\" ");
      out.print(bookingTime[0].contains("11:00")?"selected":"" );
      out.write(">11:00</option>\r\n");
      out.write("\t                            \t<option value=\"12:00\" ");
      out.print(bookingTime[0].contains("12:00")?"selected":"" );
      out.write(">12:00</option>\r\n");
      out.write("\t                            \t<option value=\"13:00\" ");
      out.print(bookingTime[0].contains("13:00")?"selected":"" );
      out.write(">13:00</option>\r\n");
      out.write("\t                            \t<option value=\"14:00\" ");
      out.print(bookingTime[0].contains("14:00")?"selected":"" );
      out.write(">14:00</option>\r\n");
      out.write("\t                            \t<option value=\"15:00\" ");
      out.print(bookingTime[0].contains("15:00")?"selected":"" );
      out.write(">15:00</option>\r\n");
      out.write("\t                            \t<option value=\"16:00\" ");
      out.print(bookingTime[0].contains("16:00")?"selected":"" );
      out.write(">16:00</option>\r\n");
      out.write("\t                            \t<option value=\"17:00\" ");
      out.print(bookingTime[0].contains("17:00")?"selected":"" );
      out.write(">17:00</option>\r\n");
      out.write("\t                            \t<option value=\"18:00\" ");
      out.print(bookingTime[0].contains("18:00")?"selected":"" );
      out.write(">18:00</option>\r\n");
      out.write("\t                            \t<option value=\"19:00\" ");
      out.print(bookingTime[0].contains("19:00")?"selected":"" );
      out.write(">19:00</option>\r\n");
      out.write("\t                            \t<option value=\"20:00\" ");
      out.print(bookingTime[0].contains("20:00")?"selected":"" );
      out.write(">20:00</option>\r\n");
      out.write("\t                            \t<option value=\"21:00\" ");
      out.print(bookingTime[0].contains("21:00")?"selected":"" );
      out.write(">21:00</option>\r\n");
      out.write("\t                            \t<option value=\"22:00\" ");
      out.print(bookingTime[0].contains("22:00")?"selected":"" );
      out.write(">22:00</option>\r\n");
      out.write("\t                            \t<option value=\"23:00\" ");
      out.print(bookingTime[0].contains("23:00")?"selected":"" );
      out.write(">23:00</option>\r\n");
      out.write("\t                            \t<option value=\"24:00\" ");
      out.print(bookingTime[0].contains("24:00")?"selected":"" );
      out.write(">24:00</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollTime2\" id=\"spaceEnrollTime2\" class=\"dp_block\">\r\n");
      out.write("\t                            \t<option value=\"\">선택</option>\r\n");
      out.write("\t                            \t<option value=\"00:00\" ");
      out.print(bookingTime[1].contains("00:00")?"selected":"" );
      out.write(">00:00</option>\r\n");
      out.write("\t                            \t<option value=\"01:00\" ");
      out.print(bookingTime[1].contains("01:00")?"selected":"" );
      out.write(">01:00</option>\r\n");
      out.write("\t                            \t<option value=\"02:00\" ");
      out.print(bookingTime[1].contains("02:00")?"selected":"" );
      out.write(">02:00</option>\r\n");
      out.write("\t                            \t<option value=\"03:00\" ");
      out.print(bookingTime[1].contains("03:00")?"selected":"" );
      out.write(">03:00</option>\r\n");
      out.write("\t                            \t<option value=\"04:00\" ");
      out.print(bookingTime[1].contains("04:00")?"selected":"" );
      out.write(">04:00</option>\r\n");
      out.write("\t                            \t<option value=\"05:00\" ");
      out.print(bookingTime[1].contains("05:00")?"selected":"" );
      out.write(">05:00</option>\r\n");
      out.write("\t                            \t<option value=\"06:00\" ");
      out.print(bookingTime[1].contains("06:00")?"selected":"" );
      out.write(">06:00</option>\r\n");
      out.write("\t                            \t<option value=\"07:00\" ");
      out.print(bookingTime[1].contains("07:00")?"selected":"" );
      out.write(">07:00</option>\r\n");
      out.write("\t                            \t<option value=\"08:00\" ");
      out.print(bookingTime[1].contains("08:00")?"selected":"" );
      out.write(">08:00</option>\r\n");
      out.write("\t                            \t<option value=\"09:00\" ");
      out.print(bookingTime[1].contains("09:00")?"selected":"" );
      out.write(">09:00</option>\r\n");
      out.write("\t                            \t<option value=\"10:00\" ");
      out.print(bookingTime[1].contains("10:00")?"selected":"" );
      out.write(">10:00</option>\r\n");
      out.write("\t                            \t<option value=\"11:00\" ");
      out.print(bookingTime[1].contains("11:00")?"selected":"" );
      out.write(">11:00</option>\r\n");
      out.write("\t                            \t<option value=\"12:00\" ");
      out.print(bookingTime[1].contains("12:00")?"selected":"" );
      out.write(">12:00</option>\r\n");
      out.write("\t                            \t<option value=\"13:00\" ");
      out.print(bookingTime[1].contains("13:00")?"selected":"" );
      out.write(">13:00</option>\r\n");
      out.write("\t                            \t<option value=\"14:00\" ");
      out.print(bookingTime[1].contains("14:00")?"selected":"" );
      out.write(">14:00</option>\r\n");
      out.write("\t                            \t<option value=\"15:00\" ");
      out.print(bookingTime[1].contains("15:00")?"selected":"" );
      out.write(">15:00</option>\r\n");
      out.write("\t                            \t<option value=\"16:00\" ");
      out.print(bookingTime[1].contains("16:00")?"selected":"" );
      out.write(">16:00</option>\r\n");
      out.write("\t                            \t<option value=\"17:00\" ");
      out.print(bookingTime[1].contains("17:00")?"selected":"" );
      out.write(">17:00</option>\r\n");
      out.write("\t                            \t<option value=\"18:00\" ");
      out.print(bookingTime[1].contains("18:00")?"selected":"" );
      out.write(">18:00</option>\r\n");
      out.write("\t                            \t<option value=\"19:00\" ");
      out.print(bookingTime[1].contains("19:00")?"selected":"" );
      out.write(">19:00</option>\r\n");
      out.write("\t                            \t<option value=\"20:00\" ");
      out.print(bookingTime[1].contains("20:00")?"selected":"" );
      out.write(">20:00</option>\r\n");
      out.write("\t                            \t<option value=\"21:00\" ");
      out.print(bookingTime[1].contains("21:00")?"selected":"" );
      out.write(">21:00</option>\r\n");
      out.write("\t                            \t<option value=\"22:00\" ");
      out.print(bookingTime[1].contains("22:00")?"selected":"" );
      out.write(">22:00</option>\r\n");
      out.write("\t                            \t<option value=\"23:00\" ");
      out.print(bookingTime[1].contains("23:00")?"selected":"" );
      out.write(">23:00</option>\r\n");
      out.write("\t                            \t<option value=\"24:00\" ");
      out.print(bookingTime[1].contains("24:00")?"selected":"" );
      out.write(">24:00</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll enrollDayOff\">\r\n");
      out.write("            \t\t\t<h5>휴무일</h5>\r\n");
      out.write("            \t\t\t<ul class=\"clearfix\">\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff0\" value=\"일요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("일요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff0\">일요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff1\" value=\"월요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("월요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff1\">월요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff2\" value=\"화요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("화요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff2\">화요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff3\" value=\"수요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("수요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff3\">수요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff4\" value=\"목요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("목요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff4\">목요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff5\" value=\"금요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("금요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff5\">금요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff6\" value=\"토요일\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("토요일")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff6\">토요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li class=\"clearfix etcDayOff\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff7\" value=\"기타\" ");
      out.print(!sDayOffDate.equals("") && sDayOffDate.contains("-")?"checked":"" );
      out.write(" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff7\">기타</label>\r\n");
      out.write("            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollDayOffETC\" disabled=\"disabled\" id=\"spaceEnrollDayOffETC\" \r\n");
      out.write("            \t\t\t\t\tvalue=\"");
      out.print(sDayOffDateArr!=null?sDayOffDateArr[sDayOffDateArr.length-1]:"" );
      out.write("\" placeholder=\"ex) 2019-08-07 ~ 2019-08-10\" />\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t</ul>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>휴무 사유</h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceEnrollDayOffEvent\" id=\"spaceEnrollDayOffEvent\" class=\"inputStyle dp_block\" value=\"");
      out.print(sDayOffEvent);
      out.write("\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"spaceEnroll-btn txt_center clearfix\">\r\n");
      out.write("            \t\t<input type=\"submit\" value=\"검수 완료\" class=\"dp_ib fw600\"/>\r\n");
      out.write("            \t\t<a href=\"javascript:goSpaceEnrollCancel();\" class=\"dp_ib fw600\">반려</a>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("        <article>\r\n");
      out.write("            <h2 id=\"f_logo\">\r\n");
      out.write("                <a href=\"index.html\" class=\"dp_block fw700\"><span>KH</span> Space</a>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <p class=\"f_info\">\r\n");
      out.write("                상호명 : 케이에이치 스페이스  |  대표 : 이호민  |  영업소재지 : 서울특별시 강남구 테헤란로 10 10길 9 <br>\r\n");
      out.write("                영업시간 : 오후 3시30분 ~ 오후 9시50분  | 대표전화 : 02)1234-1234 <br>\r\n");
      out.write("                *공간에 대한 문의사항은 해당 공간 호스트에게 문의해주세요.\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"clearfix\">\r\n");
      out.write("                <p class=\"f_info2\">\r\n");
      out.write("                    KH SPACE는 통신판매중개자이며 통신 판매의 당사자가 아닙니다. <br>\r\n");
      out.write("                    따라서 KH SPACE 는 공간 거래 정보 및 거래에 대해 책임지지 않습니다.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"cop\">Copyright KH SPACE Corp. All Rights Reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
