/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2019-08-10 15:37:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.host;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spaceEnroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1565371681360L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1565371681668L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>KH Space</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/default.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/moonspam/NanumBarunGothic@1.0/nanumbarungothicsubset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/main.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/slick.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/slick-theme.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/js/common.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/js/slick/slick.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=> {\r\n");
      out.write("\t$(\"#spaceSrch\").keyup(e => {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $sel = $(\".sel\");\r\n");
      out.write("\t\tvar $li = $(\"#autoComplete li\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(e.key == \"ArrowDown\"){\r\n");
      out.write("\t\t\tif($sel.length == 0){\r\n");
      out.write("\t\t\t\t$li.eq(0).addClass(\"sel\");\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\telse if($sel.is($li.last())){\r\n");
      out.write("\t\t\t\t//처리코드 없음\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\")\r\n");
      out.write("\t\t\t\t    .next()\r\n");
      out.write("\t\t\t\t    .addClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(e.key == \"ArrowUp\"){\r\n");
      out.write("\t\t\tif($sel.length == 0){\r\n");
      out.write("\t\t\t\t//처리코드 없음\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\telse if($sel.is($li.first())){\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$sel.removeClass(\"sel\")\r\n");
      out.write("\t\t\t\t    .prev()\r\n");
      out.write("\t\t\t\t    .addClass(\"sel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(e.key == \"Enter\"){\r\n");
      out.write("\t\t\t//값입력\r\n");
      out.write("\t\t\t$(e.target).val($sel.text());\r\n");
      out.write("\t\t\t//#autoComplete 감춤\r\n");
      out.write("\t\t\t$(\"#autoComplete\").hide()\r\n");
      out.write("\t\t\t\t\t\t\t  .children()\r\n");
      out.write("\t\t\t\t\t\t\t  .remove();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar spaceSrch = $(e.target).val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//사용자입력값이 없는 경우, 조기 리턴처리함.\r\n");
      out.write("\t\t\tif(spaceSrch.trim().length == 0)\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.print(request.getContextPath());
      out.write("/search/autoComplete.do\",\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tdata:\"spaceSrch=\"+spaceSrch,\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.trim().length == 0){\r\n");
      out.write("\t\t\t\t\t\t$(\"#autoComplete\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tvar nameArr = data.split(',');\r\n");
      out.write("\t\t\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\t\t\t$.each(nameArr, (i, name)=>{\r\n");
      out.write("\t\t\t\t\t\t\tname = name.replace(spaceSrch,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"<span class='srchVal'>\"+spaceSrch+\"</span>\");\r\n");
      out.write("\t\t\t\t\t\t\thtml += \"<li>\"+name+\"</li>\";\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#autoComplete\").html(html)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t  .fadeIn(200);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//마우스 이벤트 핸들러 추가\r\n");
      out.write("\t\t\t\t\t$(\"#autoComplete li\")\r\n");
      out.write("\t\t\t\t\t\t.click(e=>{\r\n");
      out.write("\t\t\t\t\t\t\t//값입력\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#spaceSrch\").val($(e.target).text());\r\n");
      out.write("\t\t\t\t\t\t\t//#autoComplete 감춤\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#autoComplete\").hide()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  .children()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  .remove();\r\n");
      out.write("\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t.hover(e=>{\r\n");
      out.write("\t\t\t\t\t\t\t$(e.target).addClass(\"sel\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   .siblings()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   .removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}, e=>{\r\n");
      out.write("\t\t\t\t\t\t\t$(e.target).removeClass(\"sel\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(jqxhr, textStatus, errorThrown){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"ajax처리실패!\");\r\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr, textStatus, errorThrown);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\">\r\n");
      out.write("        <h1 id=\"logo\">\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"dp_block fw700\"><span>KH</span> Space</a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div id=\"search-area\">\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() );
      out.write("/search/spaceFinder\" method=\"get\" name=\"spaceSearchFrm\"  class=\"dp_block clearfix\">\r\n");
      out.write("                <input type=\"text\" name=\"spaceSrch\" id=\"spaceSrch\" placeholder=\"지역 또는 공간유형을 검색해보세요!\">\r\n");
      out.write("                <input type=\"submit\" id=\"srchBtn\" value=\"검색\">\r\n");
      out.write("            </form>\r\n");
      out.write("                <ul id=\"autoComplete\"></ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"");
      out.print(request.getContextPath() );
      out.write("/host/spaceEnroll\" class=\"go-space dp_block\">공간 등록하기</a>\r\n");
      out.write("        <div class=\"menu-btn clearfix\">\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <p></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"nav_wrap\">\r\n");
      out.write("    \t<div>\r\n");
      out.write("\t        <div id=\"nav-top\" class=\"clearfix\">\r\n");
      out.write("\t            <div class=\"menu-close\"><img src=\"");
      out.print(request.getContextPath() );
      out.write("/images/close.png\" alt=\"\" width=\"24px\"></div>\r\n");
      out.write("\t            <div class=\"nav-ico\"></div>\r\n");
      out.write("\t            <p>\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib fw600\">로그인</a>이 필요합니다.\r\n");
      out.write("\t            </p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <nav id=\"menu\">\r\n");
      out.write("\t            <ul class=\"menu1\">\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"dp_block\">KH Space Home</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">내 정보 보기</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/booking/bookingList?userId=datbot\" class=\"dp_block\">예약 리스트</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">찜한 공간</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/customer/spaceList\" class=\"dp_block\">전체 공간보기</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">추천 공간</a></li>\r\n");
      out.write("\t                <li><a href=\"\" class=\"dp_block\">공지사항</a></li>\r\n");
      out.write("\t                <li><a href=\"");
      out.print(request.getContextPath());
      out.write("/banner/information\" class=\"dp_block\">배너 등록</a></li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </nav>\r\n");
      out.write("\t        <div id=\"nav-bottom\" class=\"txt_center\">\r\n");
      out.write("\t            <div class=\"clearfix\">\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib\">로그인</a>\r\n");
      out.write("\t                <a href=\"\" class=\"dp_ib\">회원가입</a>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <p>Copyright KH SPACE Corp. All Rights Reserved.</p>\r\n");
      out.write("\t        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"dim-layer\"></div>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/sub.css\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/spaceEnroll.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("\t$(\"#spaceEnrollFile\").on('change', fileCheck);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fileCheck(){\r\n");
      out.write("\tif($(this).val()!=\"\"){\r\n");
      out.write("\t\t//파일 용량 체크\r\n");
      out.write("\t\tvar fileSize = this.files[0].size;\r\n");
      out.write("\t\tvar maxSize = 1024*1024*10;\r\n");
      out.write("\t\tif(fileSize > maxSize){\r\n");
      out.write("\t\t\talert('파일 용량을 초과했습니다.');\r\n");
      out.write("\t\t\t$(this).val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//확장자 체크\r\n");
      out.write("\t\tvar ext = $(this).val().split(\".\").pop().toLowerCase();\r\n");
      out.write("\t\tif($.inArray(ext, [\"gif\", \"jpg\", \"jpeg\", \"png\"]) == -1){\r\n");
      out.write("\t\t\talert('이미지 확장자만 첨부해주세요.');\r\n");
      out.write("\t\t\t$(this).val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enrollValidate(){\r\n");
      out.write("\tif($(\"input[name=spaceType]:checked\").length>5){\r\n");
      out.write("\t\talert(\"공간 유형은 최대 5개까지 선택 가능합니다.\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//textarea 엔터 : 글 입력 후 DB 저장시 적용\r\n");
      out.write("\tvar str = $('#spaceIntro').val();\r\n");
      out.write("\tstr = str.replace(/(?:\\r\\n|\\r|\\n)/g, '<br/>');\r\n");
      out.write("\t$('#spaceIntro').val(str);\r\n");
      out.write("\t\r\n");
      out.write("\t//DB에서 불러와 textarea로 수정 시 <br>이 그대로 노출되는 것을 방지\r\n");
      out.write("\t//상세보기 view단에서 처리하면 될듯.\r\n");
      out.write("\t/* var str = $('#spaceIntro').val();\r\n");
      out.write("\tstr = str.split('<br/>').join(\"\\r\\n\");\r\n");
      out.write("\t$('#spaceIntro').val(str); */\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"sub_container\">\r\n");
      out.write("    <section class=\"subPage spaceEnroll\">\r\n");
      out.write("        <article>\r\n");
      out.write("        \t<div class=\"spaceEnrollTit clearfix\">\r\n");
      out.write("        \t\t<h3 class=\"tit\">어떤 공간을 공유하실건가요?</h3>\r\n");
      out.write("        \t\t<p class=\"req\">필수 선택</p>\r\n");
      out.write("        \t</div>\r\n");
      out.write("            <p class=\"req\">신중하게 공간 유형을 선택해주세요!</p>\r\n");
      out.write("            <form action=\"");
      out.print(request.getContextPath() );
      out.write("/host/spaceEnrollEnd\" name=\"spaceEnrollEndFrm\" \r\n");
      out.write("            \t\tmethod=\"post\" encType=\"multipart/form-data\" onsubmit=\"return enrollValidate();\">\r\n");
      out.write("            \t<!-- 호스트 아이디 value값 바꾸기 -->\r\n");
      out.write("            \t<input type=\"hidden\" name=\"hostId\" value=\"JeonGaNe\" />\r\n");
      out.write("            \t<div class=\"clearfix\">\r\n");
      out.write("            \t\t<h4>공간유형<span class=\"req\">*</span></h4>\r\n");
      out.write("            \t\t<p>최대 5개 선택 가능</p>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<ul class=\"facility-list space-list clearfix\">\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType0\" value=\"스터디룸\">\r\n");
      out.write("\t                    <label for=\"spaceType0\">스터디룸</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType1\" value=\"공연장\">\r\n");
      out.write("\t                    <label for=\"spaceType1\">공연장</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType2\" value=\"세미나실\">\r\n");
      out.write("\t                    <label for=\"spaceType2\">세미나실</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType3\" value=\"파티룸\">\r\n");
      out.write("\t                    <label for=\"spaceType3\">파티룸</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType4\" value=\"카페\">\r\n");
      out.write("\t                    <label for=\"spaceType4\">카페</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <input type=\"checkbox\" name=\"spaceType\" id=\"spaceType5\" value=\"기타\">\r\n");
      out.write("\t                    <label for=\"spaceType5\">기타</label>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("            \t<h4>대표이미지<span class=\"req\">*</span></h4>\r\n");
      out.write("            \t<p>이미지 사이즈 : 1024*450, 크기 : 10MB 권장</p>\r\n");
      out.write("            \t<div class=\"clearfix\">\r\n");
      out.write("            \t\t<div id=\"enrollImg1\" class=\"spaceEnroll-img\"></div>\r\n");
      out.write("            \t\t<div class=\"filebox\"> \r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFile\">파일 첨부</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFile\" id=\"spaceEnrollFile\" class=\"upload-hidden\">\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<h4>이미지</h4>\r\n");
      out.write("            \t<p>이미지 사이즈 : 1024*450, 크기 : 10MB 권장(1장당), <span>최대 3장 업로드 가능</span></p>\r\n");
      out.write("            \t<div class=\"multipleFile clearfix\">\r\n");
      out.write("            \t\t<div id=\"enrollImg2\" class=\"spaceEnroll-img\"></div>\r\n");
      out.write("            \t\t<div class=\"filebox\"> \r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg1\">파일 첨부1</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg1\" id=\"spaceEnrollFileImg1\" class=\"upload-hidden\">\r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg2\" style=\"margin: 14px 0;\">파일 첨부2</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg2\" id=\"spaceEnrollFileImg2\" class=\"upload-hidden\">\r\n");
      out.write("\t            \t\t<label for=\"spaceEnrollFileImg3\">파일 첨부3</label> \r\n");
      out.write("\t            \t\t<input type=\"file\" name=\"spaceEnrollFileImg3\" id=\"spaceEnrollFileImg3\" class=\"upload-hidden\">\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<h4>공간 정보</h4>\r\n");
      out.write("            \t<div id=\"spaceEnroll-wrap\">\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간명<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceName\" id=\"spaceName\" class=\"inputStyle dp_block\" required  placeholder=\"공간명을 입력해주세요\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간 슬로건</h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceSlogan\" id=\"spaceSlogan\" class=\"inputStyle dp_block\" placeholder=\"ex) 하루 종일 / 인원 무관\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>공간 소개<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p><textarea name=\"spaceIntro\" id=\"spaceIntro\" required class=\"dp_block\" cols=\"30\" rows=\"10\"></textarea></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>수용인원<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p>\r\n");
      out.write("            \t\t\t\t최소 :&nbsp;\r\n");
      out.write("            \t\t\t\t<span class=\"bookingsrchPrice srchPrice dp_ib\"><input type=\"number\" name=\"minBookingPeople\" required id=\"minBookingPeople\" class=\"dp_block\" /></span>\r\n");
      out.write("            \t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;최대 :&nbsp;\r\n");
      out.write("            \t\t\t\t<span class=\"bookingsrchPrice srchPrice dp_ib\"><input type=\"number\" name=\"maxBookingPeople\" required id=\"maxBookingPeople\" class=\"dp_block\" /></span>\r\n");
      out.write("            \t\t\t</p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>해시태그&nbsp;&nbsp;<span class=\"req\">쉼표(,)로 구분</span></h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"hashTag\" id=\"hashTag\" class=\"inputStyle dp_block\" placeholder=\"ex) 홍대, 카페, 홍대카페\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>편의시설</h5>\r\n");
      out.write("           \t\t\t\t<ul class=\"facility-list clearfix\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility0\" value=\"주차\">\r\n");
      out.write("                                <label for=\"facility0\">주차</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility1\" value=\"흡연\">\r\n");
      out.write("                                <label for=\"facility1\">흡연</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility2\" value=\"와이파이\">\r\n");
      out.write("                                <label for=\"facility2\">와이파이</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility3\" value=\"컴퓨터\">\r\n");
      out.write("                                <label for=\"facility3\">컴퓨터</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility4\" value=\"음식물 반입금지\">\r\n");
      out.write("                                <label for=\"facility4\">음식물 반입금지</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility5\" value=\"콘센트\">\r\n");
      out.write("                                <label for=\"facility5\">콘센트</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility6\" value=\"의자/테이블\">\r\n");
      out.write("                                <label for=\"facility6\">의자/테이블</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"facility\" id=\"facility7\" value=\"반려동물 동반 가능\">\r\n");
      out.write("                                <label for=\"facility7\">반려동물 동반 가능</label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>가격<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<p class=\"srchPrice\"><input type=\"number\" name=\"spaceEnrollPrice\" required id=\"spaceEnrollPrice\" class=\"dp_block\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll enrollDayOff\">\r\n");
      out.write("            \t\t\t<h5>이벤트</h5>\r\n");
      out.write("            \t\t\t<p>이벤트 여부</p>\r\n");
      out.write("            \t\t\t<input type=\"checkbox\" name=\"spaceEnrollEvent\" id=\"spaceEnrollEvent\" />\r\n");
      out.write("            \t\t\t<label for=\"spaceEnrollEvent\">적용</label>\r\n");
      out.write("            \t\t\t<p>정기/비정기</p>\r\n");
      out.write("            \t\t\t<div class=\"spaceEnrollEvent\">\r\n");
      out.write("            \t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollEventType\" disabled=\"disabled\" id=\"spaceEnrollAlwaysEvent\" value=\"정기 이벤트\" />\r\n");
      out.write("            \t\t\t\t<label for=\"spaceEnrollAlwaysEvent\" class=\"dp_ib\">정기 이벤트</label>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollAlwaysEventType\" id=\"spaceEnrollAlwaysEventType\" class=\"dp_block\">\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1주일\">1주일</option>\r\n");
      out.write("            \t\t\t\t\t\t<option value=\"1개월\">1개월</option>\r\n");
      out.write("            \t\t\t\t\t</select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t<div class=\"clearfix\" style=\"float:none; width:100%; padding-top:15px;\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollAlwaysEventDate\" id=\"spaceEnrollAlwaysEventDate\" placeholder=\"이벤트 주기가 1주일이면 요일을, 1개월이면 몇일인지 입력해주세요.\" class=\"dp_ib\"/>\r\n");
      out.write("            \t\t\t\t\t<p id=\"spaceEnrollAlwaysEventPrice\" class=\"srchPrice dp_ib\" style=\"margin-bottom:0;\">\r\n");
      out.write("            \t\t\t\t\t\t<input type=\"number\" name=\"spaceEnrollAlwaysEventPrice\" class=\"dp_ib\"/>\r\n");
      out.write("            \t\t\t\t\t</p>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t\t<div class=\"spaceEnrollEvent\">\r\n");
      out.write("            \t\t\t\t<div class=\"clearfix\" style=\"width:100%; float:none;\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollEventType\" disabled=\"disabled\" id=\"spaceEnrollNotAlwaysEvent\" value=\"비정기 이벤트\" />\r\n");
      out.write("\t            \t\t\t\t<label for=\"spaceEnrollNotAlwaysEvent\" class=\"dp_ib\">비정기 이벤트</label>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("\t            \t\t\t\r\n");
      out.write("\t            \t\t\t<div style=\"float:none; width:100%;\">\r\n");
      out.write("\t            \t\t\t\t<div class=\"dp_ib spaceEnrollNotAlwaysEventDate\">\r\n");
      out.write("\t            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollNotAlwaysEventStartDate\" id=\"spaceEnrollNotAlwaysEventStartDate\" placeholder=\"ex) 2019-08-09\" class=\"eventInput dp_ib\"/>\r\n");
      out.write("\t            \t\t\t\t\t~\r\n");
      out.write("\t            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollNotAlwaysEventEndDate\" id=\"spaceEnrollNotAlwaysEventEndDate\" placeholder=\"ex) 2019-08-12\" class=\"eventInput dp_ib\"/>\r\n");
      out.write("\t            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t\t<p id=\"spaceEnrollNotAlwaysEventPrice\" class=\"srchPrice dp_ib\" style=\"width:255px; margin-left:0;\"><input type=\"number\" name=\"spaceEnrollNotAlwaysEventPrice\" class=\"dp_block\" style=\"width:253px;\" /></p>\r\n");
      out.write("\t            \t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>예약 가능 시간<span class=\"req\">*</span></h5>\r\n");
      out.write("            \t\t\t<div>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollTime1\" required id=\"spaceEnrollTime1\" class=\"dp_block\">\r\n");
      out.write("\t                            \t<option value=\"00:00\">00:00</option>\r\n");
      out.write("\t                            \t<option value=\"01:00\">01:00</option>\r\n");
      out.write("\t                            \t<option value=\"02:00\">02:00</option>\r\n");
      out.write("\t                            \t<option value=\"03:00\">03:00</option>\r\n");
      out.write("\t                            \t<option value=\"04:00\">04:00</option>\r\n");
      out.write("\t                            \t<option value=\"05:00\">05:00</option>\r\n");
      out.write("\t                            \t<option value=\"06:00\">06:00</option>\r\n");
      out.write("\t                            \t<option value=\"07:00\">07:00</option>\r\n");
      out.write("\t                            \t<option value=\"08:00\">08:00</option>\r\n");
      out.write("\t                            \t<option value=\"09:00\">09:00</option>\r\n");
      out.write("\t                            \t<option value=\"10:00\">10:00</option>\r\n");
      out.write("\t                            \t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t                            \t<option value=\"12:00\">12:00</option>\r\n");
      out.write("\t                            \t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t                            \t<option value=\"14:00\">14:00</option>\r\n");
      out.write("\t                            \t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t                            \t<option value=\"16:00\">16:00</option>\r\n");
      out.write("\t                            \t<option value=\"17:00\">17:00</option>\r\n");
      out.write("\t                            \t<option value=\"18:00\">18:00</option>\r\n");
      out.write("\t                            \t<option value=\"19:00\">19:00</option>\r\n");
      out.write("\t                            \t<option value=\"20:00\">20:00</option>\r\n");
      out.write("\t                            \t<option value=\"21:00\">21:00</option>\r\n");
      out.write("\t                            \t<option value=\"22:00\">22:00</option>\r\n");
      out.write("\t                            \t<option value=\"23:00\">23:00</option>\r\n");
      out.write("\t                            \t<option value=\"24:00\">24:00</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t<div class=\"custom-select\">\r\n");
      out.write("            \t\t\t\t\t<select name=\"spaceEnrollTime2\" required id=\"spaceEnrollTime2\" class=\"dp_block\">\r\n");
      out.write("\t                            \t<option value=\"00:00\">00:00</option>\r\n");
      out.write("\t                            \t<option value=\"01:00\">01:00</option>\r\n");
      out.write("\t                            \t<option value=\"02:00\">02:00</option>\r\n");
      out.write("\t                            \t<option value=\"03:00\">03:00</option>\r\n");
      out.write("\t                            \t<option value=\"04:00\">04:00</option>\r\n");
      out.write("\t                            \t<option value=\"05:00\">05:00</option>\r\n");
      out.write("\t                            \t<option value=\"06:00\">06:00</option>\r\n");
      out.write("\t                            \t<option value=\"07:00\">07:00</option>\r\n");
      out.write("\t                            \t<option value=\"08:00\">08:00</option>\r\n");
      out.write("\t                            \t<option value=\"09:00\">09:00</option>\r\n");
      out.write("\t                            \t<option value=\"10:00\">10:00</option>\r\n");
      out.write("\t                            \t<option value=\"11:00\">11:00</option>\r\n");
      out.write("\t                            \t<option value=\"12:00\">12:00</option>\r\n");
      out.write("\t                            \t<option value=\"13:00\">13:00</option>\r\n");
      out.write("\t                            \t<option value=\"14:00\">14:00</option>\r\n");
      out.write("\t                            \t<option value=\"15:00\">15:00</option>\r\n");
      out.write("\t                            \t<option value=\"16:00\">16:00</option>\r\n");
      out.write("\t                            \t<option value=\"17:00\">17:00</option>\r\n");
      out.write("\t                            \t<option value=\"18:00\">18:00</option>\r\n");
      out.write("\t                            \t<option value=\"19:00\">19:00</option>\r\n");
      out.write("\t                            \t<option value=\"20:00\">20:00</option>\r\n");
      out.write("\t                            \t<option value=\"21:00\">21:00</option>\r\n");
      out.write("\t                            \t<option value=\"22:00\">22:00</option>\r\n");
      out.write("\t                            \t<option value=\"23:00\">23:00</option>\r\n");
      out.write("\t                            \t<option value=\"24:00\">24:00</option>\r\n");
      out.write("\t                            </select>\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t</div>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll enrollDayOff\">\r\n");
      out.write("            \t\t\t<h5>휴무일</h5>\r\n");
      out.write("            \t\t\t<ul class=\"clearfix\">\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff0\" value=\"일요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff0\">일요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff1\" value=\"월요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff1\">월요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff2\" value=\"화요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff2\">화요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff3\" value=\"수요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff3\">수요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff4\" value=\"목요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff4\">목요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff5\" value=\"금요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff5\">금요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li>\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff6\" value=\"토요일\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff6\">토요일</label>\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t\t<li class=\"clearfix etcDayOff\">\r\n");
      out.write("            \t\t\t\t\t<input type=\"checkbox\" name=\"spaceEnrollDayOff\" id=\"dayOff7\" value=\"기타\" />\r\n");
      out.write("            \t\t\t\t\t<label for=\"dayOff7\">기타</label>\r\n");
      out.write("            \t\t\t\t\t<input type=\"text\" name=\"spaceEnrollDayOffETC\" disabled=\"disabled\" id=\"spaceEnrollDayOffETC\" placeholder=\"ex) 2019-08-07 ~ 2019-08-10\" />\r\n");
      out.write("            \t\t\t\t</li>\r\n");
      out.write("            \t\t\t</ul>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t\t<div class=\"spaceEnroll\">\r\n");
      out.write("            \t\t\t<h5>휴무 사유</h5>\r\n");
      out.write("            \t\t\t<p><input type=\"text\" name=\"spaceEnrollDayOffEvent\" id=\"spaceEnrollDayOffEvent\" class=\"inputStyle dp_block\" /></p>\r\n");
      out.write("            \t\t</div>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            \t<div class=\"spaceEnroll-btn txt_center clearfix\">\r\n");
      out.write("            \t\t<input type=\"submit\" value=\"검수 신청\" class=\"dp_ib fw600\"/>\r\n");
      out.write("            \t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("\" class=\"dp_ib fw600\">취소</a>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </article>\r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("        <article>\r\n");
      out.write("            <h2 id=\"f_logo\">\r\n");
      out.write("                <a href=\"index.html\" class=\"dp_block fw700\"><span>KH</span> Space</a>\r\n");
      out.write("            </h2>\r\n");
      out.write("            <p class=\"f_info\">\r\n");
      out.write("                상호명 : 케이에이치 스페이스  |  대표 : 이호민  |  영업소재지 : 서울특별시 강남구 테헤란로 10 10길 9 <br>\r\n");
      out.write("                영업시간 : 오후 3시30분 ~ 오후 9시50분  | 대표전화 : 02)1234-1234 <br>\r\n");
      out.write("                *공간에 대한 문의사항은 해당 공간 호스트에게 문의해주세요.\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"clearfix\">\r\n");
      out.write("                <p class=\"f_info2\">\r\n");
      out.write("                    KH SPACE는 통신판매중개자이며 통신 판매의 당사자가 아닙니다. <br>\r\n");
      out.write("                    따라서 KH SPACE 는 공간 거래 정보 및 거래에 대해 책임지지 않습니다.\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"cop\">Copyright KH SPACE Corp. All Rights Reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </article>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
